CREATE DATABASE pokedex_kanto;
USE pokedex_kanto;

CREATE TABLE pokedex (
    no_pokedex INT PRIMARY KEY,
    nombre VARCHAR(50),
    tipo VARCHAR(50),
    descripcion TEXT
);

INSERT INTO pokedex (no_pokedex, nombre, tipo, descripcion) VALUES
(1, 'Bulbasaur', 'Planta/Veneno', 'Bulbasaur tiene una planta en su espalda que crece con el tiempo. Es conocido por su capacidad para usar movimientos de tipo Planta y Veneno.'),
(2, 'Ivysaur', 'Planta/Veneno', 'Ivysaur es la evolución de Bulbasaur y su planta crece más. Se vuelve más fuerte en batalla y usa ataques más poderosos.'),
(3, 'Venusaur', 'Planta/Veneno', 'Venusaur es la forma evolucionada final de Bulbasaur. La planta en su espalda florece completamente, y es muy poderoso en batallas.'),
(4, 'Charmander', 'Fuego', 'Charmander es un Pokémon de tipo Fuego con una llama en la cola que indica su salud. Es conocido por su temperamento ardiente.'),
(5, 'Charmeleon', 'Fuego', 'Charmeleon es la evolución de Charmander. Su llama se vuelve más intensa cuando está enojado. Es conocido por su actitud impetuosa.'),
(6, 'Charizard', 'Fuego/Volador', 'Charizard, la evolución final de Charmander, puede volar y su llama puede alcanzar temperaturas extremas. Es uno de los Pokémon más poderosos de su tipo.'),
(7, 'Squirtle', 'Agua', 'Squirtle es un Pokémon de tipo Agua que utiliza su caparazón para protegerse y nadar con agilidad. Es conocido por su lealtad.'),
(8, 'Wartortle', 'Agua', 'Wartortle es la evolución de Squirtle. Su caparazón se hace más grande y sus habilidades acuáticas mejoran considerablemente.'),
(9, 'Blastoise', 'Agua', 'Blastoise, la evolución final de Squirtle, tiene cañones de agua en su caparazón que puede usar en combate. Es extremadamente fuerte en batallas.'),
(10, 'Caterpie', 'Bicho', 'Caterpie es un Pokémon de tipo Bicho que evoluciona rápidamente. Es conocido por sus movimientos de tipo Bicho y su aspecto de oruga.'),
(11, 'Metapod', 'Bicho', 'Metapod es la etapa de pupa de Caterpie. Está en un capullo y está en proceso de transformación a Butterfree.'),
(12, 'Butterfree', 'Bicho/Volador', 'Butterfree es la evolución final de Caterpie. Tiene alas grandes y es conocido por su capacidad para usar movimientos de tipo Bicho y Volador.'),
(13, 'Weedle', 'Bicho/Veneno', 'Weedle es un Pokémon de tipo Bicho y Veneno. Tiene un aguijón venenoso en su cabeza que usa para defenderse.'),
(14, 'Kakuna', 'Bicho/Veneno', 'Kakuna es la etapa de pupa de Weedle. Está en un estado de inmovilidad mientras se transforma en Beedrill.'),
(15, 'Beedrill', 'Bicho/Veneno', 'Beedrill es la evolución final de Weedle. Tiene dos aguijones y es conocido por su agresividad y sus movimientos venenosos.'),
(16, 'Pidgey', 'Normal/Volador', 'Pidgey es un Pokémon de tipo Normal y Volador. Es conocido por su capacidad para volar y su comportamiento en bandadas.'),
(17, 'Pidgeotto', 'Normal/Volador', 'Pidgeotto es la evolución de Pidgey. Es más fuerte y puede volar a mayores altitudes.'),
(18, 'Pidgeot', 'Normal/Volador', 'Pidgeot es la evolución final de Pidgey. Tiene alas grandes y es muy rápido en vuelo. Es conocido por su gran habilidad en el vuelo.'),
(19, 'Rattata', 'Normal', 'Rattata es un Pokémon de tipo Normal conocido por su alta velocidad y su capacidad para morder con fuerza.'),
(20, 'Raticate', 'Normal', 'Raticate es la evolución de Rattata. Tiene colmillos afilados y es muy agresivo en combate.'),
(21, 'Spearow', 'Normal/Volador', 'Spearow es un Pokémon de tipo Normal y Volador. Es conocido por su naturaleza agresiva y su capacidad para atacar desde el aire.'),
(22, 'Fearow', 'Normal/Volador', 'Fearow es la evolución de Spearow. Tiene un gran tamaño y es muy rápido, con un pico afilado que utiliza en combate.'),
(23, 'Ekans', 'Veneno', 'Ekans es un Pokémon de tipo Veneno con forma de serpiente. Su veneno es peligroso y puede inmovilizar a sus presas.'),
(24, 'Arbok', 'Veneno', 'Arbok es la evolución de Ekans. Tiene un patrón en su cuerpo que usa para intimidar a sus enemigos y su veneno es extremadamente potente.'),
(25, 'Pikachu', 'Eléctrico', 'Pikachu es un Pokémon de tipo Eléctrico y es el ícono de la franquicia Pokémon. Es conocido por su habilidad para generar electricidad.'),
(26, 'Raichu', 'Eléctrico', 'Raichu es la evolución de Pikachu. Es más grande y su habilidad para generar electricidad es mucho más potente.'),
(27, 'Sandshrew', 'Tierra', 'Sandshrew es un Pokémon de tipo Tierra con forma de armadillo. Es conocido por su capacidad para excavar y protegerse en el suelo.'),
(28, 'Sandslash', 'Tierra', 'Sandslash es la evolución de Sandshrew. Tiene espinas en su espalda que usa para defenderse y es muy resistente.'),
(29, 'Nidoran♀', 'Veneno', 'Nidoran♀ es un Pokémon de tipo Veneno con un pequeño cuerno en su frente. Es conocido por su naturaleza defensiva.'),
(30, 'Nidorina', 'Veneno', 'Nidorina es la evolución de Nidoran♀. Tiene un tamaño mayor y es conocida por su agresividad en combate.'),
(31, 'Nidoqueen', 'Veneno/Tierra', 'Nidoqueen es la evolución final de Nidoran♀. Es muy poderosa y tiene una gran resistencia en batalla.'),
(32, 'Nidoran♂', 'Veneno', 'Nidoran♂ es un Pokémon de tipo Veneno con un cuerno en su frente. Es conocido por su naturaleza territorial.'),
(33, 'Nidorino', 'Veneno', 'Nidorino es la evolución de Nidoran♂. Tiene un cuerno más grande y es muy agresivo en combate.'),
(34, 'Nidoking', 'Veneno/Tierra', 'Nidoking es la evolución final de Nidoran♂. Es extremadamente fuerte y tiene un cuerno poderoso que usa en batalla.'),
(35, 'Clefairy', 'Hada', 'Clefairy es un Pokémon de tipo Hada conocido por su capacidad para usar movimientos de tipo Hada y su actitud alegre.'),
(36, 'Clefable', 'Hada', 'Clefable es la evolución de Clefairy. Es conocido por su habilidad para cambiar su forma y su habilidad para usar movimientos de tipo Hada con eficacia.'),
(37, 'Vulpix', 'Fuego', 'Vulpix es un Pokémon de tipo Fuego con seis colas. Es conocido por su belleza y su habilidad para lanzar llamas.'),
(38, 'Ninetales', 'Fuego', 'Ninetales es la evolución de Vulpix. Tiene nueve colas y es conocido por su habilidad para lanzar llamas y su longevidad.'),
(39, 'Jigglypuff', 'Normal/Hada', 'Jigglypuff es un Pokémon de tipo Normal y Hada. Es conocido por su habilidad para cantar una canción que induce el sueño.'),
(40, 'Wigglytuff', 'Normal/Hada', 'Wigglytuff es la evolución de Jigglypuff. Su habilidad para cantar y su gran capacidad pulmonar lo hacen un adversario difícil en combate.'),
(41, 'Zubat', 'Veneno/Volador', 'Zubat es un Pokémon de tipo Veneno y Volador conocido por su habilidad para volar en la oscuridad y su ataque de mordida venenosa.'),
(42, 'Golbat', 'Veneno/Volador', 'Golbat es la evolución de Zubat. Tiene un tamaño mayor y es conocido por su habilidad para absorber salud de sus oponentes.'),
(43, 'Oddish', 'Planta/Veneno', 'Oddish es un Pokémon de tipo Planta y Veneno con una planta en su cabeza. Es conocido por su habilidad para liberar esporas venenosas.'),
(44, 'Gloom', 'Planta/Veneno', 'Gloom es la evolución de Oddish. Tiene un aroma desagradable que utiliza para repeler a los enemigos y su habilidad para usar movimientos de tipo Planta y Veneno.'),
(45, 'Vileplume', 'Planta/Veneno', 'Vileplume es la evolución final de Oddish. Tiene una enorme flor en su cabeza que libera esporas venenosas y es muy poderoso en combate.'),
(46, 'Paras', 'Bicho/Planta', 'Paras es un Pokémon de tipo Bicho y Planta con hongos en su espalda que le ayudan a obtener nutrientes del suelo.'),
(47, 'Parasect', 'Bicho/Planta', 'Parasect es la evolución de Paras. Los hongos en su espalda crecen mucho más y se vuelven muy poderosos en combate.'),
(48, 'Venonat', 'Bicho/Veneno', 'Venonat es un Pokémon de tipo Bicho y Veneno con ojos grandes que le permiten detectar a sus enemigos con facilidad.'),
(49, 'Venomoth', 'Bicho/Veneno', 'Venomoth es la evolución de Venonat. Tiene alas grandes y es conocido por su habilidad para liberar un polvo venenoso.'),
(50, 'Diglett', 'Tierra', 'Diglett es un Pokémon de tipo Tierra que vive bajo tierra. Es conocido por su velocidad para excavar y moverse rápidamente.'),
(51, 'Dugtrio', 'Tierra', 'Dugtrio es la evolución de Diglett. Está compuesto por tres Diglett unidos que se mueven bajo tierra con gran velocidad.'),
(52, 'Meowth', 'Normal', 'Meowth es un Pokémon de tipo Normal que se parece a un gato. Es conocido por su habilidad para usar el movimiento "Pay Day" para recolectar dinero.'),
(53, 'Persian', 'Normal', 'Persian es la evolución de Meowth. Es un Pokémon elegante y rápido, conocido por su agilidad en combate.'),
(54, 'Psyduck', 'Agua', 'Psyduck es un Pokémon de tipo Agua conocido por sus dolores de cabeza, que pueden desencadenar poderes psíquicos en momentos de estrés.'),
(55, 'Golduck', 'Agua', 'Golduck es la evolución de Psyduck. Es un Pokémon rápido y poderoso en el agua, conocido por su habilidad para usar ataques acuáticos.'),
(56, 'Mankey', 'Lucha', 'Mankey es un Pokémon de tipo Lucha con un temperamento explosivo. Es conocido por su habilidad para usar movimientos de tipo Lucha con gran fuerza.'),
(57, 'Primeape', 'Lucha', 'Primeape es la evolución de Mankey. Su ira es legendaria y su fuerza en combate es muy grande.'),
(58, 'Growlithe', 'Fuego', 'Growlithe es un Pokémon de tipo Fuego que se asemeja a un cachorro de león. Es conocido por su lealtad y su habilidad para usar ataques de fuego.'),
(59, 'Arcanine', 'Fuego', 'Arcanine es la evolución de Growlithe. Es un Pokémon majestuoso y rápido con gran fuerza en batalla y habilidades de fuego.'),
(60, 'Poliwag', 'Agua', 'Poliwag es un Pokémon de tipo Agua con una apariencia de renacuajo. Es conocido por su habilidad para nadar y usar ataques acuáticos.'),
(61, 'Poliwhirl', 'Agua', 'Poliwhirl es la evolución de Poliwag. Su capacidad para nadar y su fuerza en combate aumentan considerablemente.'),
(62, 'Poliwrath', 'Agua/Lucha', 'Poliwrath es la evolución final de Poliwag. Combina habilidades acuáticas con técnicas de lucha en combate.'),
(63, 'Abra', 'Psíquico', 'Abra es un Pokémon de tipo Psíquico conocido por su habilidad para teletransportarse y su fuerte poder psíquico.'),
(64, 'Kadabra', 'Psíquico', 'Kadabra es la evolución de Abra. Su poder psíquico es aún más fuerte, y usa una varita para canalizar sus habilidades.'),
(65, 'Alakazam', 'Psíquico', 'Alakazam es la evolución final de Abra. Tiene una memoria increíble y un poder psíquico formidable.'),
(66, 'Machop', 'Lucha', 'Machop es un Pokémon de tipo Lucha con un cuerpo musculoso. Es conocido por su fuerza física y su habilidad para usar movimientos de lucha.'),
(67, 'Machoke', 'Lucha', 'Machoke es la evolución de Machop. Tiene una gran musculatura y es extremadamente fuerte en combate.'),
(68, 'Machamp', 'Lucha', 'Machamp es la evolución final de Machop. Es conocido por su fuerza sobrehumana y su habilidad para usar cuatro brazos en combate.'),
(69, 'Bellsprout', 'Planta/Veneno', 'Bellsprout es un Pokémon de tipo Planta y Veneno con una apariencia de planta trepadora. Es conocido por su habilidad para usar ataques de tipo Planta y Veneno.'),
(70, 'Weepinbell', 'Planta/Veneno', 'Weepinbell es la evolución de Bellsprout. Tiene una forma de campana y usa su cuerpo para atrapar a sus presas.'),
(71, 'Victreebel', 'Planta/Veneno', 'Victreebel es la evolución final de Bellsprout. Es un Pokémon muy peligroso con una boca grande que usa para atrapar a sus presas.'),
(72, 'Tentacool', 'Agua/Veneno', 'Tentacool es un Pokémon de tipo Agua y Veneno con una apariencia de medusa. Es conocido por su capacidad para liberar tentáculos venenosos.'),
(73, 'Tentacruel', 'Agua/Veneno', 'Tentacruel es la evolución de Tentacool. Tiene tentáculos más largos y venenosos que usa para defenderse y atacar a sus enemigos.'),
(74, 'Geodude', 'Roca/Tierra', 'Geodude es un Pokémon de tipo Roca y Tierra con un cuerpo rocoso. Es conocido por su gran resistencia y fuerza física.'),
(75, 'Graveler', 'Roca/Tierra', 'Graveler es la evolución de Geodude. Su cuerpo rocoso es aún más resistente y puede rodar para atacar a sus enemigos.'),
(76, 'Golem', 'Roca/Tierra', 'Golem es la evolución final de Geodude. Es extremadamente resistente y puede usar su cuerpo rocoso para causar grandes daños en combate.'),
(77, 'Ponyta', 'Fuego', 'Ponyta es un Pokémon de tipo Fuego que se asemeja a un caballo. Es conocido por su habilidad para correr a gran velocidad y lanzar llamas.'),
(78, 'Rapidash', 'Fuego', 'Rapidash es la evolución de Ponyta. Es un Pokémon rápido y poderoso con una melena de fuego que puede atacar a sus enemigos.'),
(79, 'Slowpoke', 'Agua/Psíquico', 'Slowpoke es un Pokémon de tipo Agua y Psíquico que se mueve lentamente. Es conocido por su actitud relajada y su habilidad para usar movimientos psíquicos.'),
(80, 'Slowbro', 'Agua/Psíquico', 'Slowbro es la evolución de Slowpoke. Su actitud relajada no cambia, pero su fuerza y habilidades en combate aumentan considerablemente.'),
(81, 'Magnemite', 'Eléctrico/Acero', 'Magnemite es un Pokémon de tipo Eléctrico y Acero. Se adhiere a objetos metálicos y usa imanes para atacar a sus enemigos.'),
(82, 'Magneton', 'Eléctrico/Acero', 'Magneton es la evolución de Magnemite. Está compuesto por tres Magnemite unidos y tiene una gran capacidad para generar electricidad.'),
(83, 'Farfetch\'d', 'Normal/Volador', 'Farfetch\'d es un Pokémon de tipo Normal y Volador conocido por llevar un puerro. Es conocido por su habilidad para usar ataques con este vegetal.'),
(84, 'Doduo', 'Normal/Volador', 'Doduo es un Pokémon de tipo Normal y Volador con dos cabezas. Es conocido por su velocidad y sus ataques coordinados.'),
(85, 'Dodrio', 'Normal/Volador', 'Dodrio es la evolución de Doduo. Tiene tres cabezas y es conocido por su gran velocidad y habilidad para atacar en equipo.'),
(86, 'Seel', 'Agua', 'Seel es un Pokémon de tipo Agua con apariencia de foca. Es conocido por su habilidad para nadar y su piel resbaladiza.'),
(87, 'Dewgong', 'Agua/Hielo', 'Dewgong es la evolución de Seel. Tiene habilidades tanto acuáticas como de hielo, y es conocido por su elegancia en el agua.'),
(88, 'Grimer', 'Veneno', 'Grimer es un Pokémon de tipo Veneno que tiene un cuerpo amorfo y puede contaminar el suelo. Es conocido por su habilidad para usar ataques venenosos.'),
(89, 'Muk', 'Veneno', 'Muk es la evolución de Grimer. Su cuerpo es aún más viscoso y su capacidad para liberar veneno es muy peligrosa.'),
(90, 'Shellder', 'Agua', 'Shellder es un Pokémon de tipo Agua con una concha dura que protege su cuerpo. Es conocido por su habilidad para usar ataques de tipo Agua.'),
(91, 'Cloyster', 'Agua/Hielo', 'Cloyster es la evolución de Shellder. Tiene una concha aún más dura y es conocido por su habilidad para usar ataques de tipo Agua e Hielo.'),
(92, 'Gastly', 'Fantasma', 'Gastly es un Pokémon de tipo Fantasma con un cuerpo de gas. Es conocido por su habilidad para flotar y atacar con movimientos fantasmas.'),
(93, 'Haunter', 'Fantasma', 'Haunter es la evolución de Gastly. Tiene un cuerpo más sólido y es conocido por su habilidad para asustar y atacar con movimientos fantasmas.'),
(94, 'Gengar', 'Fantasma/Veneno', 'Gengar es la evolución final de Gastly. Es muy poderoso en combate y su habilidad para usar ataques fantasmas y venenosos es temida.'),
(95, 'Onix', 'Roca/Tierra', 'Onix es un Pokémon de tipo Roca y Tierra con un cuerpo de roca en forma de serpiente. Es conocido por su gran tamaño y fuerza.'),
(96, 'Drowzee', 'Psíquico', 'Drowzee es un Pokémon de tipo Psíquico que usa su habilidad para inducir el sueño en sus enemigos y alimentarse de sus sueños.'),
(97, 'Hypno', 'Psíquico', 'Hypno es la evolución de Drowzee. Su habilidad para inducir el sueño es aún más potente, y puede controlar las mentes de sus enemigos.'),
(98, 'Krabby', 'Agua', 'Krabby es un Pokémon de tipo Agua con apariencia de cangrejo. Es conocido por sus fuertes pinzas y su habilidad para nadar.'),
(99, 'Kingler', 'Agua', 'Kingler es la evolución de Krabby. Tiene pinzas más grandes y es conocido por su gran fuerza y habilidades acuáticas.'),
(100, 'Voltorb', 'Eléctrico', 'Voltorb es un Pokémon de tipo Eléctrico con forma de esfera. Es conocido por su habilidad para explotar y generar electricidad.'),
(101, 'Electrode', 'Eléctrico', 'Electrode es la evolución de Voltorb. Es aún más rápido y su habilidad para generar electricidad es aún más poderosa.'),
(102, 'Exeggcute', 'Planta/Psíquico', 'Exeggcute es un Pokémon de tipo Planta y Psíquico compuesto por varios huevos. Es conocido por su habilidad para usar ataques psíquicos.'),
(103, 'Exeggutor', 'Planta/Psíquico', 'Exeggutor es la evolución de Exeggcute. Tiene un cuerpo grande y puede usar habilidades de tipo Planta y Psíquico con gran eficacia.'),
(104, 'Cubone', 'Tierra', 'Cubone es un Pokémon de tipo Tierra que lleva un cráneo en la cabeza. Es conocido por su naturaleza solitaria y sus ataques de tipo Tierra.'),
(105, 'Marowak', 'Tierra', 'Marowak es la evolución de Cubone. Utiliza el cráneo de su madre como un arma en combate y es conocido por su fuerza y resistencia.'),
(106, 'Hitmonlee', 'Lucha', 'Hitmonlee es un Pokémon de tipo Lucha conocido por sus habilidades en artes marciales y su capacidad para realizar poderosos patadas.'),
(107, 'Hitmonchan', 'Lucha', 'Hitmonchan es un Pokémon de tipo Lucha con habilidades para lanzar poderosos puñetazos. Es conocido por su estilo de combate basado en el boxeo.'),
(108, 'Lickitung', 'Fantasma', 'Lickitung es un Pokémon de tipo Fantasma conocido por su lengua larga y pegajosa, que utiliza para atacar a sus enemigos.'),
(109, 'Koffing', 'Veneno', 'Koffing es un Pokémon de tipo Veneno con un cuerpo lleno de gases. Es conocido por su habilidad para liberar nubes de veneno en combate.'),
(110, 'Weezing', 'Veneno', 'Weezing es la evolución de Koffing. Tiene dos esferas de gas en su cuerpo y es conocido por su capacidad para liberar veneno en grandes cantidades.'),
(111, 'Rhyhorn', 'Tierra/Roca', 'Rhyhorn es un Pokémon de tipo Tierra y Roca con un cuerpo robusto y un cuerno afilado. Es conocido por su gran fuerza física.'),
(112, 'Rhydon', 'Tierra/Roca', 'Rhydon es la evolución de Rhyhorn. Tiene un tamaño mayor y una fuerza aún más poderosa, así como una gran capacidad para atacar en combate.'),
(113, 'Chansey', 'Normal', 'Chansey es un Pokémon de tipo Normal conocido por su habilidad para curar a otros Pokémon y su naturaleza amable y protectora.'),
(114, 'Tangela', 'Planta', 'Tangela es un Pokémon de tipo Planta con un cuerpo cubierto de enredaderas. Es conocido por su habilidad para usar movimientos de tipo Planta.'),
(115, 'Kangaskhan', 'Normal', 'Kangaskhan es un Pokémon de tipo Normal conocido por su habilidad para llevar a su cría en una bolsa en su abdomen y su gran fuerza física.'),
(116, 'Horsea', 'Agua', 'Horsea es un Pokémon de tipo Agua con una apariencia de caballo marino. Es conocido por su habilidad para nadar y lanzar chorros de agua.'),
(117, 'Seadra', 'Agua', 'Seadra es la evolución de Horsea. Tiene una apariencia más elegante y puede lanzar chorros de agua con gran precisión.'),
(118, 'Goldeen', 'Agua', 'Goldeen es un Pokémon de tipo Agua que se asemeja a un pez. Es conocido por su habilidad para nadar y lanzar ataques acuáticos.'),
(119, 'Seaking', 'Agua', 'Seaking es la evolución de Goldeen. Tiene cuernos afilados y es conocido por su gran fuerza y habilidades acuáticas.'),
(120, 'Staryu', 'Agua', 'Staryu es un Pokémon de tipo Agua con forma de estrella. Es conocido por su capacidad para regenerar sus partes perdidas y su habilidad para usar ataques acuáticos.'),
(121, 'Starmie', 'Agua/Psíquico', 'Starmie es la evolución de Staryu. Tiene un núcleo en el centro de su cuerpo que emite un brillo. Es conocido por su habilidad para usar movimientos de tipo Agua y Psíquico.'),
(122, 'Mr. Mime', 'Psíquico/Hada', 'Mr. Mime es un Pokémon de tipo Psíquico y Hada conocido por su habilidad para crear barreras de energía y su comportamiento enigmático.'),
(123, 'Scyther', 'Bicho/Volador', 'Scyther es un Pokémon de tipo Bicho y Volador con garras afiladas en sus brazos. Es conocido por su gran velocidad y habilidad en combate.'),
(124, 'Jynx', 'Hielo/Psíquico', 'Jynx es un Pokémon de tipo Hielo y Psíquico conocido por su habilidad para usar movimientos de tipo Hielo y su apariencia inusual.'),
(125, 'Electabuzz', 'Eléctrico', 'Electabuzz es un Pokémon de tipo Eléctrico conocido por su habilidad para generar electricidad y su aspecto de simio eléctrico.'),
(126, 'Magmar', 'Fuego', 'Magmar es un Pokémon de tipo Fuego con una apariencia de ave de fuego. Es conocido por su habilidad para lanzar llamas intensas.'),
(127, 'Pinsir', 'Bicho', 'Pinsir es un Pokémon de tipo Bicho con pinzas afiladas que usa para capturar y aplastar a sus enemigos.'),
(128, 'Tauros', 'Normal', 'Tauros es un Pokémon de tipo Normal que se asemeja a un toro. Es conocido por su fuerza y su actitud agresiva en combate.'),
(129, 'Magikarp', 'Agua', 'Magikarp es un Pokémon de tipo Agua conocido por su habilidad para saltar y su apariencia de pez. Es famoso por su evolución a Gyarados.'),
(130, 'Gyarados', 'Agua/Dragón', 'Gyarados es la evolución de Magikarp. Es un Pokémon muy poderoso con una apariencia de dragón y habilidades acuáticas formidables.'),
(131, 'Lapras', 'Agua/Hielo', 'Lapras es un Pokémon de tipo Agua y Hielo conocido por su gran tamaño y su habilidad para nadar con gran elegancia.'),
(132, 'Ditto', 'Normal', 'Ditto es un Pokémon de tipo Normal que tiene la habilidad de transformarse en cualquier otro Pokémon. Es conocido por su habilidad para imitar.'),
(133, 'Eevee', 'Normal', 'Eevee es un Pokémon de tipo Normal conocido por sus múltiples evoluciones posibles, lo que le permite adaptarse a varios tipos.'),
(134, 'Vaporeon', 'Agua', 'Vaporeon es una de las evoluciones de Eevee. Es de tipo Agua y es conocido por su habilidad para nadar y su apariencia de sirena.'),
(135, 'Jolteon', 'Eléctrico', 'Jolteon es una de las evoluciones de Eevee. Es de tipo Eléctrico y es conocido por su velocidad y su capacidad para generar electricidad.'),
(136, 'Flareon', 'Fuego', 'Flareon es una de las evoluciones de Eevee. Es de tipo Fuego y es conocido por su habilidad para lanzar llamas intensas.'),
(137, 'Porygon', 'Normal', 'Porygon es un Pokémon de tipo Normal que tiene un cuerpo digital y puede adaptar su forma para diferentes usos.'),
(138, 'Porygon2', 'Normal', 'Porygon2 es la evolución de Porygon. Tiene un cuerpo más avanzado y es conocido por su habilidad para procesar información de manera eficiente.'),
(139, 'Porygon-Z', 'Normal', 'Porygon-Z es la evolución final de Porygon. Su cuerpo es aún más avanzado y tiene una gran capacidad para adaptarse a diferentes situaciones.'),
(140, 'Omanyte', 'Roca/Agua', 'Omanyte es un Pokémon de tipo Roca y Agua con una concha espiral en su cuerpo. Es conocido por su apariencia de nautilus y sus habilidades acuáticas.'),
(141, 'Omastar', 'Roca/Agua', 'Omastar es la evolución de Omanyte. Tiene una concha más grande y puede usar habilidades acuáticas y rocosas en combate.'),
(142, 'Kabuto', 'Roca/Agua', 'Kabuto es un Pokémon de tipo Roca y Agua con una concha dura y una apariencia de trilobite. Es conocido por su capacidad para nadar rápidamente.'),
(143, 'Kabutops', 'Roca/Agua', 'Kabutops es la evolución de Kabuto. Tiene una apariencia más agresiva y usa sus afiladas garras para atacar a sus enemigos.'),
(144, 'Aerodactyl', 'Roca/Volador', 'Aerodactyl es un Pokémon de tipo Roca y Volador con apariencia de pterosaurio. Es conocido por su gran velocidad y habilidades aéreas.'),
(145, 'Snorlax', 'Normal', 'Snorlax es un Pokémon de tipo Normal conocido por su gran tamaño y su naturaleza perezosa. Es conocido por su habilidad para dormir y resistir ataques.'),
(146, 'Articuno', 'Hielo/Volador', 'Articuno es un Pokémon legendario de tipo Hielo y Volador conocido por su habilidad para controlar el hielo y el frío.'),
(147, 'Zapdos', 'Eléctrico/Volador', 'Zapdos es un Pokémon legendario de tipo Eléctrico y Volador conocido por su habilidad para generar electricidad y controlar tormentas.'),
(148, 'Moltres', 'Fuego/Volador', 'Moltres es un Pokémon legendario de tipo Fuego y Volador conocido por su habilidad para lanzar llamas y su majestuosa apariencia.'),
(149, 'Dratini', 'Dragón', 'Dratini es un Pokémon de tipo Dragón conocido por su apariencia de serpiente y su capacidad para evolucionar en poderosos dragones.'),
(150, 'Dragonair', 'Dragón', 'Dragonair es la evolución de Dratini. Tiene una apariencia elegante y puede usar habilidades de tipo Dragón con gran eficacia.'),
(151, 'Dragonite', 'Dragón/Volador', 'Dragonite es la evolución final de Dratini. Es un Pokémon poderoso con habilidades de tipo Dragón y Volador, conocido por su gran fuerza y agilidad.');

SELECT * FROM pokedex